### ISSUE TITLE
日期时间类型同步的问题

### ISSUE THREAD

**Issue by GpsLypy** [toventang/debezium-client#2]
现在我从kafka 读取的消息中解析出一个日期类型的字段为 epProjectCreateDate:1662199261000
![image](https://user-images.githubusercontent.com/80027734/188252344-c393c5d3-1136-41ed-91f4-f9b377f43c17.png)

我的问题是这个解析出来字段的类型是int64类型表示的时间戳，而我的mysql对应的字段 epProjectCreateDate类型是decmial(3) 
我同步过去发现变成了下面这个样子，有什么办法可以解决吗？
![image](https://user-images.githubusercontent.com/80027734/188252285-62c4fd5d-c91e-40e5-be2e-fa8deeafec2c.png)

**Comment by GpsLypy** [comment]
我感觉这个问题应该无解吧 kafka 的消息类型不够丰富，比如解析出来一个int64类型的值，根本没办法确切的知道该值是时间戳类型还是别的什么，所以也就无法在mysql端回放出来

**Comment by toventang** [comment]
你这个是 mysql 字段类型问题了，int64 对应 mysql 的 bigint，用 decimal(3) 长度不够的。
另外你截图的这个并不是 decimal 而是 datetime 类型呢。

**Comment by toventang** [comment]
你这个是 mysql 字段类型问题了，int64 对应 mysql 的 bigint，用 decimal(3) 长度不够的。
另外你截图的这个并不是 decimal 而是 datetime 类型呢。

**Comment by GpsLypy** [comment]
![c60135a464a1f09792d6c7829e76134](https://user-images.githubusercontent.com/80027734/188532049-0a1beb53-5fbe-4838-b0b7-70a633ab6699.jpg)
大佬 你解析kafka消息的时候解析了语义类型嘛？比如下面这个name
![d7814dc284559c694dd5061ca1ddfae](https://user-images.githubusercontent.com/80027734/188532414-28ee93bb-4b4e-42f1-b037-e14b479c740e.jpg)

**Comment by GpsLypy** [comment]
像上面那种如果有了语义类型的话，假设我们解析到了kafka字段某个类型是int64类型，但是可以根据其语义类型可以得知他真正的类型是·timestamp

**Comment by GpsLypy** [comment]
![image](https://user-images.githubusercontent.com/80027734/188533088-ec368010-5769-42d0-8365-2bf03249fbbd.png)
我看了一下这个struct里面应该是没有name字段
![image](https://user-images.githubusercontent.com/80027734/188533205-1e8df600-b926-4ada-971c-438bf25e3c20.png)

**Comment by toventang** [comment]
> 

现在没有自动同步表结构，需要先创建目标表结构。不同目标数据库类型的某些字段类型可能想要不一样，比如 Elasticsearch 在某些业务场景下 int64 精度丢失，就需要在 Elasticsearch 里改为字符串了。

**Comment by GpsLypy** [comment]
enen 是的 但是我的意思是可以把name解析出来会更好些
<img width="489" alt="1662430812110" src="https://user-images.githubusercontent.com/80027734/188533778-e557869c-bc14-485b-92ad-2650495c3054.png">
